farb-dir: lib/l10n
output-dir: lib/l10n/gen
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales:
  - en
use-deferred-loading: true
synthetic-package: false