name: mvp
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  flutter_spinkit: ^5.1.0
  google_fonts: ^3.0.1
  equatable: ^2.0.5
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  flutter_calendar_carousel: ^2.4.1
  fl_chart: ^0.55.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1

flutter_gen:
  output: lib/src/gen/
  integrations:
    flutter_svg: true
    

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
